name: Build Java WAR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code from repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Java environment
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'

    # Step 3: Cache Maven dependencies
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Step 4: Build the WAR file
    - name: Build with Maven
      run: mvn clean package

    # Step 5: Upload the WAR file as an artifact
    - name: Upload WAR Artifact
      uses: actions/upload-artifact@v3
      with:
        name: java-webapp-war
        path: WARS/*.war
