name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Change this to your desired branch
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up JDK
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17' # Change this to your Java version

    # Step 3: Build the WAR file
    - name: Build WAR File
      run: mvn clean package -DskipTests # Update if using Gradle

    # Step 4: Build Docker Image
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Display war file name
      run: ls -ltr target/
      
    - name: Build and Tag Docker Image
      run: |
        docker build --build-arg WAR_FILE=target/your-app.war -t your-dockerhub-username/your-app:latest .

    # Step 5: Push Docker Image
    - name: Push Docker Image
      run: docker push your-dockerhub-username/your-app:latest
